language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  secure: "P1WXTdrqiihFPpjz5gSj7eyToLcEwfsaY9LLYUJei+a6VnAmNH66f99w7CSA6cFATpU4NgPrcVDSekxNDIY4CeQAUSo/BQArf0z3cTXVi9kNyA5BQsqhV5lTD0DM8AJCorXZ2dBpVA7L9rhTmzACLsRL4qn3NVY5oEzx9KY737M="

cache:
  directories:
    - $HOME/.cache/pip
  pip: true

sudo: false

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# command to install dependencies
addons:
  apt:
    packages:
    - libatlas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy=1.9 scipy=0.16 nose pandas
  - pip install mock
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:  python setup.py test