language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  secure:
    - "HmDJDvvk6o5QNrHI9s7wQLlaOdMWLmWNxZ2X4vm6u5avTbzJiGYRQFaCnDKdl9hxQBWyURlEnLA4NkrSdmvNiTY5rSHvInRDFQiBvMjFhs8cFRxULQ3dvavJMawI+gtLnchiJsvJr8deJE9W2zBEWzBN+dM6az/c4UK+KFkFI0o="
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=openml
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7"
      NUMPY_VERSION="1.6.2" SCIPY_VERSION="0.11.0" CYTHON_VERSION="0.21"
    - DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="true"
      NUMPY_VERSION="1.10.2" SCIPY_VERSION="0.16.1" CYTHON_VERSION="0.23.4"
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"
      NUMPY_VERSION="1.10.2" SCIPY_VERSION="0.16.1" CYTHON_VERSION="0.23.4"

install: source ci_scripts/install.sh
script: bash ci_scripts/test.sh
after_success: source ci_scripts/success.sh
